config/routes.rb
FriendCircle::Application.routes.draw do

  shallow do resources :users do
      resources :posts
      resources :circles
    end
  end
  resource :session

  get "/feed" => "posts#feed"

  root to: "posts#feed"

end

app/models/circle.rb
class Circle < ActiveRecord::Base
  validates :name, :user_id, presence: true
  validates :name, uniqueness: { scope: :user_id }

  belongs_to :user

  has_many :circle_memberships, inverse_of: :circle

  has_many :members, through: :circle_memberships, source: :user

  has_many :post_shares
  has_many :posts, through: :post_shares, source: :post
end

app/models/circle_membership.rb
class CircleMembership < ActiveRecord::Base
  validates :circle, :user_id, presence: true
  validates :user_id, uniqueness: { scope: :circle_id }

  belongs_to :circle
  belongs_to :user
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :url, :post, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :links, inverse_of: :post
  has_many :post_shares, inverse_of: :post
  has_many :circles, through: :post_shares, source: :circle
  has_many :viewers, through: :circles, source: :members

  validates :user_id, :body, :title, presence: true
end

app/models/post_share.rb
class PostShare < ActiveRecord::Base
  validates :circle_id, :post, presence: true

  belongs_to :circle
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_reader :password

  #circle associations
  has_many :circles
  has_many :circle_members, through: :circles, source: :members

  #post associations
  has_many :posts

  #membership associations
  has_many :circle_memberships
  has_many :member_circles, through: :circle_memberships, source: :circle

  #validations
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  before_validation :ensure_session_token

  def password=(password)
    unless password.blank?
      @password = password
      self.password_digest = BCrypt::Password.create(password)
    end
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(params)
    user = User.find_by(email: params[:email])
    return nil if user.nil?
    return user if user.is_password?(params[:password])
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    return self.session_token
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :ensure_signed_in

  helper_method :current_user, :signed_in?, :current_user?

  def login_user(user)
    session[:token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:token])
  end

  def signed_in?
    !!current_user
  end

  def current_user?(user)
    current_user == user
  end


  private

  def ensure_signed_in
    redirect_to new_session_url unless signed_in?
  end

  def ensure_current_user
    unless current_user?(User.find(params[:user_id]))
      flash[:errors] = "Not You!"
      redirect_to user_url(current_user)
    end
  end
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController

  before_action :ensure_current_user, only: [:new, :create]

  def new
    @circle = Circle.new
  end

  def create
    @circle = current_user.circles.new(circle_params)

    if @circle.save
      redirect_to circle_url(@circle)
    else
      flash.now[:errors] = @circle.errors.full_messages
      render :new
    end

  end

  def edit
    @circle = Circle.find(params[:id])
    ensure_circle_owner
  end

  def update
    @circle = Circle.find(params[:id])
    ensure_circle_owner

    if @circle.update(circle_params)
      redirect_to circle_url(@circle)
    else
      flash.now[:errors] = @circle.errors.full_messages
      render :edit
    end
  end

  def index
    @circles = current_user.circles
  end


  def show
    @circle = Circle.find(params[:id])
  end

  private

  def circle_params
    params.require(:circle).permit(:name, member_ids: [])
  end

  def ensure_circle_owner
    redirect_to circle_url(@circle) unless current_user?(@circle.user)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :ensure_current_user, only: [:new, :create]

  def new
    @post = Post.new
    3.times { @post.links.new }
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.links.new(link_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def feed
    @posts = Post.joins(:viewers).where("circle_memberships.user_id = ?", current_user.id)
  end
  
  def index
    @posts = current_user.posts
  end

  private

  def post_params
    params.require(:post).permit(:body, :title, circle_ids: [])
  end

  def link_params
    params.permit(links: :url)
          .require(:links)
          .values
          .reject { |url| url.values.all?(&:blank?) }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :ensure_signed_in, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by_credentials(user_params)

    if @user
      login_user(@user)
      redirect_to root_url
    else
      flash.now[:errors] = "Wrong username or password"
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:token] = nil
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :ensure_signed_in, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end


  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token_input
      "<input
          type=\"hidden\"
          name=\"authenticity_token\"
          value=\"#{ form_authenticity_token }\">".html_safe
    end

end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/circles/_form.html.erb
<% action = @circle.persisted? ?
  circle_url(@circle) :
  user_circles_url(current_user) %>

<form action="<%= action %>" method="POST">

  <%= auth_token_input %>

  <% if @circle.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label>Circle Name
    <input type="text" name="circle[name]" value="<%= @circle.name %>">
  </label>

  <br>

  Users:
  <br>
    <input type="hidden" name="circle[member_ids][]" value="">
    <% User.all.each do |user| %>
      <label>
        <input
          type="checkbox"
          name="circle[member_ids][]"
          value="<%= user.id %>"
          <%= "checked" if @circle.members.include?(user) %>
          >
          <%= user.email %>
        </input>
      </label>

      <br>

    <% end %>

  <input type="submit"
      value="<%= @circle.persisted? ? "Edit" : "Create" %> Circle">

</form>

app/views/circles/edit.html.erb
<h1>Edit <%= @circle.name %></h1>

  <%= render "form" %>

app/views/circles/index.html.erb
<h1>My Circles</h1>

<ul>
<% @circles.each do |circle| %>
 <li><%= link_to circle.name, circle_url(circle) %></li>
 <% end %>
</ul>

app/views/circles/new.html.erb
<h1>Create a Circle</h1>

  <%= render "form" %>

app/views/circles/show.html.erb
<h1><%= @circle.name %></h1>

<ul>
  <% @circle.members.each do |member| %>
  <li>
    <a href="<%= user_url(member) %>"><%= member.email %></a>
  </li>
  <% end %>
</ul>

<% if @circle.user == current_user %>
  <%= link_to "Edit Circle", edit_circle_url(@circle) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FriendCircle</title>
  <!-- <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %> -->
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <%= debug params %>
  <%= debug session[:token] %>
  <hr>
</header>

<nav>
  <ul>
    <li><%= link_to "Home", root_url %></li>
    <% if signed_in? %>
      <li><%= link_to "Create Circle", new_user_circle_url(current_user) %></li>
      <li><%= link_to "Create Post", new_user_post_url(current_user) %></li>
      <li><%= link_to "My Circles", user_circles_url(current_user) %></li>
      <li><%= link_to "My Posts", user_posts_url(current_user) %></li>
      <li><%= button_to "Logout", session_url, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign Up", new_user_url %></li>
      <li><%= link_to "Sign In", new_session_url %></li>
    <% end %>
  </ul>
</nav>

<%= flash[:errors] if flash[:errors] %>
<%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<h2><%= post.title %></h2>
<p><%= post.body %></p>
<br>
<ul>
  <% post.links.each do |link| %>
    <li><%= link.url %></li>
  <% end %>
</ul>
<p>------------------------------</p>
<br>

app/views/posts/feed.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
<%= render 'post', post: post %>
<% end %>

app/views/posts/index.html.erb
<h1>My Posts</h1>

<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post_url(post) %></li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%=  user_posts_url %>" method="POST">

  <%= auth_token_input %>

  Choose Circles:

    <% current_user.circles.each do |circle| %>


      <label>
        <input type="checkbox"
          name="post[circle_ids][]"
          value="<%= circle.id %>">
        <%= circle.name %>
        </input>
      </label>

    <% end %>

    <br>

    <label>Title
      <input type="text" name="post[title]" value="<%= @post.title %>">
    </label>
    <br>

    <label>Post:
      <br>
      <textarea name="post[body]"><%= @post.body %></textarea>
    </label>

    <br>
    <% @post.links.each_with_index do |link, i| %>
      <label>Link #<%= i + 1 %>
        <input type="text" name="links[<%= link.object_id %>][url]">
      <label>
    <% end %>

    <br>

    <input type="submit" value="Create Post">
</form>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

  <p><%= @post.body %></p>
  <br>

  <ul>
    <% @post.links.each do |link| %>
      <li><%= link.url %></li>
    <% end %>
  </ul>

  <br>
  <p>Shared with:</p>
  <ul>
    <% @post.circles.each do |circle| %>
    <li>
      <a href="<%= circle_url(circle) %>"><%= circle.name %></a>
    </li>
    <% end %>
  </ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
  <%= auth_token_input %>

  <label>Email
    <input type="text" name="user[email]">
  </label>

  <label>Password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">

</form>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>